# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nompy0.2.2.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 734)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.searchBox = QtWidgets.QLineEdit(self.widget)
        self.searchBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setText("")
        self.searchBox.setFrame(True)
        self.searchBox.setCursorPosition(0)
        self.searchBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchBox.setReadOnly(False)
        self.searchBox.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.searchBox.setClearButtonEnabled(False)
        self.searchBox.setObjectName("searchBox")
        self.verticalLayout_5.addWidget(self.searchBox)
        self.dishIngredientTabWidget = QtWidgets.QTabWidget(self.widget)
        self.dishIngredientTabWidget.setObjectName("dishIngredientTabWidget")
        self.dishesTab = QtWidgets.QWidget()
        self.dishesTab.setObjectName("dishesTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dishesTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dishList = QtWidgets.QListWidget(self.dishesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dishList.sizePolicy().hasHeightForWidth())
        self.dishList.setSizePolicy(sizePolicy)
        self.dishList.setMinimumSize(QtCore.QSize(284, 0))
        self.dishList.setObjectName("dishList")
        self.horizontalLayout.addWidget(self.dishList)
        self.dishIngredientTabWidget.addTab(self.dishesTab, "")
        self.ingredientsTab = QtWidgets.QWidget()
        self.ingredientsTab.setObjectName("ingredientsTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ingredientsTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ingredientList = QtWidgets.QListWidget(self.ingredientsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ingredientList.sizePolicy().hasHeightForWidth())
        self.ingredientList.setSizePolicy(sizePolicy)
        self.ingredientList.setMinimumSize(QtCore.QSize(284, 0))
        self.ingredientList.setProperty("isWrapping", False)
        self.ingredientList.setObjectName("ingredientList")
        self.horizontalLayout_4.addWidget(self.ingredientList)
        self.dishIngredientTabWidget.addTab(self.ingredientsTab, "")
        self.verticalLayout_5.addWidget(self.dishIngredientTabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(5, 100, 5, 100)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonAddDish = QtWidgets.QPushButton(self.widget)
        self.buttonAddDish.setObjectName("buttonAddDish")
        self.verticalLayout_3.addWidget(self.buttonAddDish)
        self.buttonRemoveDish = QtWidgets.QPushButton(self.widget)
        self.buttonRemoveDish.setObjectName("buttonRemoveDish")
        self.verticalLayout_3.addWidget(self.buttonRemoveDish)
        self.dishBrowser = QtWidgets.QTextBrowser(self.widget)
        self.dishBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dishBrowser.sizePolicy().hasHeightForWidth())
        self.dishBrowser.setSizePolicy(sizePolicy)
        self.dishBrowser.setMaximumSize(QtCore.QSize(100, 166))
        self.dishBrowser.setObjectName("dishBrowser")
        self.verticalLayout_3.addWidget(self.dishBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dishAddedTable = QtWidgets.QTableWidget(self.widget)
        self.dishAddedTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dishAddedTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dishAddedTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dishAddedTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.dishAddedTable.setGridStyle(QtCore.Qt.NoPen)
        self.dishAddedTable.setCornerButtonEnabled(False)
        self.dishAddedTable.setObjectName("dishAddedTable")
        self.dishAddedTable.setColumnCount(2)
        self.dishAddedTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.dishAddedTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dishAddedTable.setHorizontalHeaderItem(1, item)
        self.dishAddedTable.horizontalHeader().setVisible(True)
        self.dishAddedTable.horizontalHeader().setCascadingSectionResizes(True)
        self.dishAddedTable.horizontalHeader().setDefaultSectionSize(30)
        self.dishAddedTable.horizontalHeader().setHighlightSections(False)
        self.dishAddedTable.horizontalHeader().setMinimumSectionSize(28)
        self.dishAddedTable.horizontalHeader().setSortIndicatorShown(False)
        self.dishAddedTable.horizontalHeader().setStretchLastSection(True)
        self.dishAddedTable.verticalHeader().setVisible(False)
        self.dishAddedTable.verticalHeader().setDefaultSectionSize(20)
        self.dishAddedTable.verticalHeader().setHighlightSections(False)
        self.dishAddedTable.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.dishAddedTable)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonMinusQty = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMinusQty.sizePolicy().hasHeightForWidth())
        self.buttonMinusQty.setSizePolicy(sizePolicy)
        self.buttonMinusQty.setMinimumSize(QtCore.QSize(140, 0))
        self.buttonMinusQty.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buttonMinusQty.setObjectName("buttonMinusQty")
        self.horizontalLayout_3.addWidget(self.buttonMinusQty, 0, QtCore.Qt.AlignLeft)
        self.buttonPlusQty = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlusQty.sizePolicy().hasHeightForWidth())
        self.buttonPlusQty.setSizePolicy(sizePolicy)
        self.buttonPlusQty.setMinimumSize(QtCore.QSize(140, 0))
        self.buttonPlusQty.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonPlusQty.setObjectName("buttonPlusQty")
        self.horizontalLayout_3.addWidget(self.buttonPlusQty, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.outputBrowser = QtWidgets.QTextBrowser(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputBrowser.sizePolicy().hasHeightForWidth())
        self.outputBrowser.setSizePolicy(sizePolicy)
        self.outputBrowser.setMinimumSize(QtCore.QSize(0, 200))
        self.outputBrowser.setObjectName("outputBrowser")
        self.verticalLayout_6.addWidget(self.outputBrowser)
        MainWindow.setCentralWidget(self.widget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 742, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.dishIngredientTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nompy 0.2.2"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.dishIngredientTabWidget.setTabText(self.dishIngredientTabWidget.indexOf(self.dishesTab), _translate("MainWindow", "Dishes"))
        self.dishIngredientTabWidget.setTabText(self.dishIngredientTabWidget.indexOf(self.ingredientsTab), _translate("MainWindow", "Ingredients"))
        self.buttonAddDish.setText(_translate("MainWindow", "Add Dish"))
        self.buttonRemoveDish.setText(_translate("MainWindow", "Remove Item"))
        self.dishBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Dish stats</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Calories:<br />Fat:<br />Sat. Fat:<br />Carbs:<br />Fiber:<br />Protein:<br />Salt:<br />Iron:</span></p></body></html>"))
        item = self.dishAddedTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Qty"))
        item = self.dishAddedTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dish / Ingredient"))
        self.buttonMinusQty.setText(_translate("MainWindow", "-"))
        self.buttonPlusQty.setText(_translate("MainWindow", "+"))
        self.outputBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Meal stats</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

